### PR TITLE
Undo hardcoding fonts path in setFont()

### PR DESCRIPTION
**Pull request by Propaganistas**

### CODE REVIEW

**Comment by uyab** [comment]
I wonder if this is considered as breaking changes and should included in next major release, any thought ?

**Comment by Propaganistas** [comment]
It will break if the configuration file was published since the new config syntax including the full path isn't defined in such case.

**Comment by Propaganistas** [comment]
Actually it would make sense to have this package still working without requiring the fonts to be published.

**Comment by uyab** [comment]
Please check https://github.com/laravolt/avatar/commit/1c9048c5688c25deb6af899fee0e458aab334557

**Comment by Propaganistas** [comment]
Great; good job!

**Pull request closed without merging**
